[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Luuk Blankenstijn <git@luukblankenstijn.nl>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/LuukBlankenstijn/Scuttlecast"

[workspace.dependencies]
scuttlecast = { path = "crates/scuttlecast", version = "0.1.0" }
async-stream = "0.3"
bincode = "2.0"
clap = { version = "4.6.6", features = ["derive"] }
derive_more = "2.1.1"
futures-core = "0.3"
futures-util = "0.3"
proptest = "1"
proptest-derive = "0.6"
rand = "0.10.2"
socket2 = "0.6.5"
thiserror = "2.0"
tokio = "1"
bon = "3.9.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tempfile = "3"
bytes = "1.12.1"
reed-solomon-erasure = "6.0.0"
