[package]
name = "scuttlecast"
version = "0.1.0"
edition = "2024"

[dependencies]
proto.workspace = true
async-stream.workspace = true
derive_more = { workspace = true, features = ["constructor"] }
futures-core.workspace = true
futures-util.workspace = true
rand.workspace = true
socket2.workspace = true
thiserror.workspace = true
bon.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "fs",
    "io-std",
    "io-util",
    "net",
    "sync",
    "time",
] }
