[profile.default]
slow-timeout = { period = "10s", terminate-after = 3 }
fail-fast = false

[test-groups]
network = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'kind(test)'
test-group = 'network'
